version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    platform: linux/amd64
    image: share-bill-frontend
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    platform: linux/amd64
    image: share-bill-backend
    ports:
      - "5050:5050"

  mongodb:
    image: mongo:latest
    platform: linux/amd64