version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    platform: linux/amd64
    env_file:
      - ./frontend/.env.prod
    image: share-bill-frontend
    ports:
      - "5051:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    platform: linux/amd64
    env_file:
      - ./backend/.env.prod
    image: share-bill-backend
    ports:
      - "5050:5050"